### PR TITLE
Remove materialize and fix legend with custom javascript and css styles

### PR DESCRIPTION
**Pull request by chitech**
Removed the materialize library and added custom javascript and css styles for the legend.

### CODE REVIEW

**Comment by paulvill** [comment]
Hi Christine @chitech, it looks great! Thanks a lot!!

Do you think that you could try to integrate your solution in the file  layout_test/integrated-view  which combines all the progress from MozSprint (the template with the viewport and the list of dataset in the footer) ? I am attaching a screen shot where the question mark should be

questionmarkposition

Let me know if you can take on this task!

In any case, thanks a lot for going back to your code!

**Comment by paulvill** [comment]
Also the legend keys has been simplified since last week. 

It is now for all datasets

    right/left arrow: forward/backward in time
    up/down arrow: zoom in/out
    space bar/double click: change between the channels
    'A','S','D','W': rotate in 3D

But no worries, I can edit that myself.

**Comment by chitech** [comment]
Hi @paulvill, 
Sure I will update the layout so the question mark appears in the upper right corner. I will also try to merge the feature-legend branch to your layout_test master branch.  I will create a pull request once its done.

**Comment by paulvill** [comment]
Thanks Christine @chitech !

**Pull request merged**
